[workspace]
members = [
"lab_1",
"lab_4",
"lab_5",
"lab_6",
"lab_7/server",
"lab_7/client",
"lab_8/server",
"lab_8/client",
"lab_9",
"lab_10",
"lab_11",
"lab_12"
]
exclude = [
    "lab_7/shared",
    "lab_8/shared"
]