[config]
default_to_workspace = false

[tasks.rollup]
script_runner = "@shell"
script = ''' 
rollup ./lab_${@}/client/main.js --format iife --file ./lab_${@}/client/pkg/package.js
'''

[tasks.build_client]
description = "Build client"
install_crate = { crate_name = "wasm-pack", binary = "wasm-pack", test_arg = "-V" }
command = "wasm-pack"
args = ["build", "./lab_${@}/client", "--target", "web", "--out-name", "package", "--dev"]

[tasks.build_server]
description = "Build server"
command = "cargo"
args = ["build","--package", "server${@}"]

[tasks.start]
description = "Build and start Actix server with client on port 8100"
command = "cargo"
args = ["run", "--package", "server${@}"]
dependencies = ["build_client", "build_server", "rollup"]

