//! SeaORM Entity. Generated by sea-orm-codegen 0.3.2
use dotenv::dotenv;
use std::env;
use sea_orm::*;


pub async fn estabilish_connection() -> DatabaseConnection {
    dotenv().ok();
    let database_url = env::var("DATABASE_URL")
        .expect("DATABASE_URL must be set");
    Database::connect(database_url).await.unwrap()
}